# Generated by Django 3.0 on 2019-12-10 03:20

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = ['bar.json', 'restaurant.json', 'station.json', 'toilets.json']


def load_data(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for filename in DATA_FILENAME:
        jsonfile = Path(__file__).parents[2] / filename

        with open(str(jsonfile)) as datafile:
            objects = json.load(datafile)
            for obj in objects['elements']:
                try:
                    obj_type = obj['type']
                    if obj_type == 'node':
                        tags = obj['tags']
                        name = tags.get('name', 'no-name')
                        longitude = obj.get('lon', 0)
                        latitude = obj.get('lat', 0)
                        location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                        house_number = tags.get('addr:housenumber')
                        street = tags.get('addr:street', '')
                        house_number = house_number + ' ' if house_number else ''
                        Place(name=name,
                            location=location,
                            address=f'{house_number}{street}',
                            city='Dublin',
                            category=filename.split('.')[0]
                            ).save()
                except KeyError:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
